/*
 * OpenTTD Content API
 *
 * OpenTTD Content API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigUserAudiencesGet200ResponseInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "settings-url", skip_serializing_if = "Option::is_none")]
    pub settings_url: Option<String>,
}

impl ConfigUserAudiencesGet200ResponseInner {
    pub fn new() -> ConfigUserAudiencesGet200ResponseInner {
        ConfigUserAudiencesGet200ResponseInner {
            name: None,
            description: None,
            settings_url: None,
        }
    }
}


