/*
 * OpenTTD Content API
 *
 * OpenTTD Content API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Dependency {
    #[serde(rename = "content-type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<crate::models::ContentType>,
    #[serde(rename = "unique-id", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<String>,
    #[serde(rename = "md5sum-partial", skip_serializing_if = "Option::is_none")]
    pub md5sum_partial: Option<String>,
}

impl Dependency {
    pub fn new() -> Dependency {
        Dependency {
            content_type: None,
            unique_id: None,
            md5sum_partial: None,
        }
    }
}


