/*
 * OpenTTD Content API
 *
 * OpenTTD Content API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionMinimizedAllOfLicense {
}

impl VersionMinimizedAllOfLicense {
    pub fn new() -> VersionMinimizedAllOfLicense {
        VersionMinimizedAllOfLicense {
        }
    }
}


