[package]
name = "openttd-runner-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
fs_extra = "1.3.0"
mongodb = { version = "2.8.1", features = ["tokio-sync"] }
regex = "1.10.3"
rust-ini = "0.20.0"
serde = { version = "1.0.197", features = ["derive"] }
tempfile = "3.10.0"
