[package]
name = "openttd-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
openttd-runner-lib = { path = "../openttd-runner-lib" }
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
